#!/bin/bash
# =============================================================================
# Raspberry Pi DHCP Server Setup for Arduino Uno x6 Network
# Hardware: Cisco Catalyst 3560-CX switch, Arduino Uno w/ Ethernet Shields
# =============================================================================
# Usage:
#   chmod +x setup_pi_dhcp.sh
#   sudo ./setup_pi_dhcp.sh
# =============================================================================

set -e  # Exit on any error

# --- CONFIGURATION -----------------------------------------------------------
# Edit these values to match your desired network layout

PI_STATIC_IP="192.168.1.1"
SUBNET_MASK="255.255.255.0"
SUBNET="192.168.1.0"
DHCP_RANGE_START="192.168.1.100"
DHCP_RANGE_END="192.168.1.200"
LEASE_TIME="86400"           # 24 hours in seconds
ETHERNET_IFACE="eth0"        # Pi's Ethernet interface (verify with: ip link show)

# Reserved IPs for each Arduino (fill in MAC addresses after first discovery boot)
# Format: "HOSTNAME MAC_ADDRESS RESERVED_IP"
# MACs will be AA:BB:CC:DD:EE:XX as placeholders — see Step 2 in README
ARDUINO_RESERVATIONS=(
    "arduino1 00:00:00:00:00:01 192.168.1.101"
    "arduino2 00:00:00:00:00:02 192.168.1.102"
    "arduino3 00:00:00:00:00:03 192.168.1.103"
    "arduino4 00:00:00:00:00:04 192.168.1.104"
    "arduino5 00:00:00:00:00:05 192.168.1.105"
    "arduino6 00:00:00:00:00:06 192.168.1.106"
)

# --- COLOUR OUTPUT -----------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warning() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# --- ROOT CHECK --------------------------------------------------------------
[[ $EUID -ne 0 ]] && error "Run this script with sudo."

echo ""
echo "============================================================"
echo "  Pi DHCP Server Setup — Arduino Uno x6 Network"
echo "============================================================"
echo ""

# --- STEP 1: Detect Ethernet Interface ---------------------------------------
info "Detecting Ethernet interface..."
if ! ip link show "$ETHERNET_IFACE" &>/dev/null; then
    warning "'$ETHERNET_IFACE' not found. Available interfaces:"
    ip link show | grep -E '^[0-9]+:' | awk '{print "  " $2}'
    error "Edit ETHERNET_IFACE in this script to match your interface name."
fi
success "Using interface: $ETHERNET_IFACE"

# --- STEP 2: Assign Static IP to Pi ------------------------------------------
info "Configuring static IP $PI_STATIC_IP on $ETHERNET_IFACE..."

DHCPCD_CONF="/etc/dhcpcd.conf"
# Remove any existing eth0 static block to avoid duplicates
sed -i '/^# Pi static — added by setup_pi_dhcp/,/^$/d' "$DHCPCD_CONF" 2>/dev/null || true

cat >> "$DHCPCD_CONF" <<EOF

# Pi static — added by setup_pi_dhcp
interface $ETHERNET_IFACE
static ip_address=$PI_STATIC_IP/24
static routers=$PI_STATIC_IP
static domain_name_servers=8.8.8.8
EOF

success "Static IP configured in dhcpcd.conf"

# --- STEP 3: Install isc-dhcp-server -----------------------------------------
info "Installing isc-dhcp-server..."
apt-get update -qq
apt-get install -y isc-dhcp-server > /dev/null
success "isc-dhcp-server installed"

# --- STEP 4: Bind DHCP server to eth0 ----------------------------------------
info "Binding DHCP server to $ETHERNET_IFACE..."
DHCP_DEFAULT="/etc/default/isc-dhcp-server"
sed -i "s/^INTERFACESv4=.*/INTERFACESv4=\"$ETHERNET_IFACE\"/" "$DHCP_DEFAULT"
success "DHCP server bound to $ETHERNET_IFACE"

# --- STEP 5: Write dhcpd.conf ------------------------------------------------
info "Writing DHCP server configuration..."

DHCPD_CONF="/etc/dhcp/dhcpd.conf"
cp "$DHCPD_CONF" "${DHCPD_CONF}.bak.$(date +%s)" 2>/dev/null || true

cat > "$DHCPD_CONF" <<EOF
# =============================================================================
# dhcpd.conf — Raspberry Pi DHCP server for Arduino Uno x6
# Generated by setup_pi_dhcp.sh
# =============================================================================

default-lease-time $LEASE_TIME;
max-lease-time $LEASE_TIME;
authoritative;

subnet $SUBNET netmask $SUBNET_MASK {
    range $DHCP_RANGE_START $DHCP_RANGE_END;
    option subnet-mask $SUBNET_MASK;
    option routers $PI_STATIC_IP;
    option domain-name-servers 8.8.8.8;

    # ------------------------------------------------------------------
    # Arduino MAC reservations
    # Replace MAC addresses with real values discovered via:
    #   cat /var/lib/dhcp/dhcpd.leases
    # after first boot with all Arduinos connected.
    # ------------------------------------------------------------------
EOF

for entry in "${ARDUINO_RESERVATIONS[@]}"; do
    read -r hostname mac ip <<< "$entry"
    cat >> "$DHCPD_CONF" <<EOF

    host $hostname {
        hardware ethernet $mac;
        fixed-address $ip;
    }
EOF
done

echo "}" >> "$DHCPD_CONF"

success "dhcpd.conf written to $DHCPD_CONF"

# --- STEP 6: Validate dhcpd.conf ---------------------------------------------
info "Validating DHCP config..."
if dhcpd -t -cf "$DHCPD_CONF" 2>/dev/null; then
    success "DHCP config is valid"
else
    warning "Config validation returned warnings — check $DHCPD_CONF manually"
fi

# --- STEP 7: Enable and start the service ------------------------------------
info "Enabling isc-dhcp-server to start on boot..."
systemctl enable isc-dhcp-server
systemctl restart isc-dhcp-server || warning "Service start failed — likely because MAC addresses are still placeholders. Update them and run: sudo systemctl restart isc-dhcp-server"
success "DHCP server enabled"

# --- STEP 8: Apply static IP (requires reboot or manual apply) ---------------
info "Applying static IP without full reboot..."
ip addr flush dev "$ETHERNET_IFACE" 2>/dev/null || true
ip addr add "$PI_STATIC_IP/24" dev "$ETHERNET_IFACE" 2>/dev/null || true
ip link set "$ETHERNET_IFACE" up

# --- DONE --------------------------------------------------------------------
echo ""
echo "============================================================"
echo -e "  ${GREEN}Setup complete!${NC}"
echo "============================================================"
echo ""
echo "  Pi IP address : $PI_STATIC_IP"
echo "  DHCP range    : $DHCP_RANGE_START – $DHCP_RANGE_END"
echo "  Arduino IPs   : 192.168.1.101 – 192.168.1.106 (after MAC update)"
echo ""
echo -e "  ${YELLOW}NEXT STEPS:${NC}"
echo "  1. Connect all 6 Arduinos (with Ethernet Shields) to the switch"
echo "  2. Run: cat /var/lib/dhcp/dhcpd.leases"
echo "  3. Copy real MAC addresses into this script's ARDUINO_RESERVATIONS"
echo "  4. Re-run this script OR run: sudo ./update_mac_reservations.sh"
echo "  5. Reboot the Pi: sudo reboot"
echo "  6. Configure Simulink targets to IPs 192.168.1.101–106"
echo ""
echo "  Useful commands:"
echo "    sudo systemctl status isc-dhcp-server   # Check DHCP health"
echo "    cat /var/lib/dhcp/dhcpd.leases          # See connected devices"
echo "    ping 192.168.1.101                      # Test Arduino 1"
echo ""
